# OPENCART_PORT=8081 PHPADMIN_PORT=8888 LOCAL_IP=$(hostname -I | grep -o "^[0-9.]*") docker compose up -d

version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'
    networks:
      - default

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    networks:
      - default

  opencart:
    image: docker.io/bitnami/opencart:4.0.2-3
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.80.1:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - default

  tests:
    image: tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - OPENCART_URL=http://opencart:8080
    volumes:
      - ./reports:/app/reports  # Для сохранения Allure-отчетов
      - ./tests:/app/tests  # Для подключения тестов
    depends_on:
      - opencart
    entrypoint: >
       ["/app/wait-for-it.sh", "opencart", "8080", "--", "pytest", "tests", "--browser", "chrome", "--browser-version", "114.0", "--alluredir=/app/reports"]
    networks:
      - default

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local

networks:
  default:
    name: selenoid
    external: true